# serverless.yml

service: aws-serverless-express-application

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
Resources:
  Type: 'AWS::S3::Bucket'
  Properties:
    BucketName: hmuralid-serverless-bucket-123456789